# -*- coding: utf-8 -*-
"""Primera pre-entrega Poderoso.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prDwZNqe4HMDkOXNdZLiLyUJd7IowUp5

Consigna

Crear un programa que permita emular el registro y almacenamiento de usuarios en una base de datos.
Crear el programa utilizando el concepto de funciones, diccionarios, bucles y condicionales.

Sugerencias

El formato de registro es: Nombre de usuario y Contraseña.

Utilizar una función para almacenar la información y otra función para mostrar la información.

Utilizar un diccionario para almacenar dicha información, con el par usuario-contraseña (clave-valor).

Utilizar otra función para el login de usuarios, comprobando que la contraseña coincida con el usuario.
"""

import json
from google.colab import drive
drive.mount('/drive/')

def singin(usuarios):#Funcion para ingresar datos y crear el archivo

  nombre=input('Ingrese su nombre de usuario: ')

  while nombre in usuarios:

    nombre=input('Ingrese otro: ')

  contraseña=input('Ingrese su contraseña de usuario: ')

  usuarios.update({nombre: contraseña})

  with open('datos.json','w') as file:
    json.dump(usuarios, file, indent=4)

  return usuarios

def login():#Funcion para logear usuarios

  with open('datos.json') as file:
    usuarios = json.load(file)

  nombre= input('Ingrese su nombre de usuario: ')

  if nombre in usuarios:

    contraseña=input('Ingrese su contraseña de usuario: ')

    if usuarios[nombre]==contraseña:

      print('Usted a ingresado ')

    else:
      for i in range(3):#comprobacion de password con 3 intentos

        contraseña=input('A ingresado mal la contraseña\nVuelva a intentar')

        if usuarios[nombre]==contraseña:
          print('Usted a ingresado')
          break
        elif i==2: print('se agotaron los intentos')

  else:

    print('nombre inexistente')

user={}

while True:

  eleccion=input('\nElija que accion desea realizar \n Login \n Singin \n Salir \n')

  if eleccion.lower()=='singin':

    singin(user)

  elif eleccion.lower()=='login':

    login()

    break

  elif eleccion.lower()=='salir':

    break